// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // if (kIsWeb) {
    //   print("FirebaseOptions kIsWeb");
    //   return web;
    // }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        print("FirebaseOptions kIsWeb");
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8o5J9VbHCNp1sCCo4ubGtswA559iY-PQ',
    appId: '1:389273765439:android:06ad82bafa5d0873c3da8a',
    messagingSenderId: '383294896292',
    projectId: 'bala-expense-tracker',
    storageBucket: 'bala-expense-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCM7HloaBR-ssXimYx9m3NmxeKMJad0CQ',
    appId: '1:389273765439:ios:65d19d07702512e3c3da8a',
    messagingSenderId: '383294896292',
    projectId: 'com.bala.tracker',
    storageBucket: 'bala-expense-tracker.appspot.com',
    iosClientId: '335311491157-c5flgeet9q75j3nrujvpjp21hljn7f5c.apps.googleusercontent.com',
    iosBundleId: 'com.bala.tracker',
  );
  // static const FirebaseOptions web = FirebaseOptions(
  //     apiKey: "AIzaSyBrPfvXeqeJx_QrxsdFyRIk6KySKWg5CYg",
  //     authDomain: "forward-vial-328510.firebaseapp.com",
  //     projectId: "forward-vial-328510",
  //     storageBucket: "forward-vial-328510.appspot.com",
  //     messagingSenderId: "383294896292",
  //     appId: "1:383294896292:web:6454b779bae88b38fd8e31",
  //     measurementId: "G-T7MGQS6W9S");

}

